export BOOST_DIR=/Users/oscarraig/bitbucket/rebuild-graph/boost/
export DYNAMIC_LIBRARY_PATH_MAC=DYLD_LIBRARY_PATH
export DYNAMIC_LIBRARY_PATH_LINUX=LD_LIBRARY_PATH
#export DYNAMIC_LIBRARY_PATH=$DYNAMIC_LIBRARY_PATH_LINUX
export DYNAMIC_LIBRARY_PATH=$DYNAMIC_LIBRARY_PATH_MAC

export RUN_COMMAND=$DYNAMIC_LIBRARY_PATH=${BOOST_DIR}lib/
