sudo: required

language: c

services:
  - docker

before_install:
  - docker pull oscarraig/gsl-boost

script:
  - docker run -v `pwd`:/home/ oscarraig/gsl-boost  /bin/sh -c "cd /home; ./configure && make && make test"


