


comm_exp: graphs.cpp main.cpp rebuildgraph.cpp
	g++ -stdlib=libstdc++ main.cpp graphs.cpp CTrace.cpp rebuildgraph.cpp -L. -lgsl -lgslcblas -stdlib=libstdc++ -lboost_program_options -I gsl-1.16/  -I. -o comm_exp
