
regress:
	make -C graph_gslgraph/test run

clean:
	make -C graph_gslgraph/test clean
	make -C graph_analyze/test clean
	make -C graph_compare/test clean
	make -C graph_core/test clean
	make -C graph_gslgraph/test clean
